build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "aws-sdk-cpp/1.7.7"
    CONAN_USERNAME: "kmaragon"
    CONAN_LOGIN_USERNAME: "kmaragon"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/kmaragon/conan"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1


    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Debug

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Debug

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
